[package]
name = "lc"
version = "0.1.0"
authors = ["Kat0w1ce <kato.szy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
